apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.employeeName }}-harness
  labels:
    app.kubernetes.io/name: employee-harness
    app.kubernetes.io/instance: {{ .Values.employeeName }}
  annotations:
    star.employee/recipe: {{ .Values.employeeName }}
automountServiceAccountToken: false
